---
run:
  timeout: "5m"
output:
  sort-results: true
linters-settings:
  goimports:
    local-prefixes: "github.com/chihaya/chihaya"
  staticcheck:
    checks:
      - "all"
      - "-SA1019"  # Allow netErr.Temporary
  gosec:
    excludes:
      - "G404"  # Allow the usage of math/rand
linters:
  enable:
    - "bidichk"
    - "bodyclose"
    - "deadcode"
    - "errcheck"
    - "errname"
    - "errorlint"
    - "gofumpt"
    - "goimports"
    - "goprintffuncname"
    - "gosec"
    - "gosimple"
    - "govet"
    - "ifshort"
    - "importas"
    - "ineffassign"
    - "makezero"
    - "prealloc"
    - "predeclared"
    - "revive"
    - "rowserrcheck"
    - "staticcheck"
    - "structcheck"
    - "stylecheck"
    - "tenv"
    - "typecheck"
    - "unconvert"
    - "unused"
    - "varcheck"
    - "wastedassign"
    - "whitespace"
issues:
  include:
    - "EXC0012"  # Exported should have comment
    - "EXC0012"  # Exported should have comment
    - "EXC0013"  # Package comment should be of form
    - "EXC0014"  # Comment on exported should be of form
    - "EXC0015"  # Should have a package comment
