# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "precise64"
    config.vm.box_url = "http://files.vagrantup.com/precise64.box"
    config.vm.network :public_network
    config.vm.network :forwarded_port, guest: 8000, host: 8080
    config.vm.synced_folder "../", "/home/vagrant/chihaya/src/github.com/pushrax/chihaya"

    config.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--name", "chihaya"]
    end

    config.vm.provision :puppet do |puppet|
        puppet.manifests_path = "puppet/manifests"
        puppet.manifest_file = "default.pp"
        puppet.module_path = "puppet/modules"
    end
end
