name: "Build & Test"
on:
  push:
    branches:
      - "!dependabot/*"
      - "*"
  pull_request:
    branches:
      - "*"
jobs:
  build:
    name: "Build Binary"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0" # v7.0.0
      - uses: "actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16" # v6.5.0
        with:
          go-version-file: "go.mod"
      - name: "Run Go Build"
        run: "VERBOSE=1 make build"
  image-build:
    name: "Build Container Image"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0" # v7.0.0
      - uses: "docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf" # v7.2.0
  unit:
    name: "Run Unit Tests"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0" # v7.0.0
      - uses: "actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16" # v6.5.0
        with:
          go-version-file: "go.mod"
      - name: "Run Go Test"
        run: "VERBOSE=1 make test-unit"
  e2e:
    name: "E2E Tests"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: go.mod
      - name: "Install redis"
        run: "sudo apt-get update && sudo apt-get install redis"
      - name: "Run end-to-end tests"
        run: "make test-e2e"
  helm:
    name: "Helm Template"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: "Install Helm"
        uses: "engineerd/configurator@v0.0.5"
        with:
          name: "helm"
          pathInArchive: "linux-amd64/helm"
          fromGitHubReleases: true
          repo: "helm/helm"
          version: "^v3"
          urlTemplate: "https://get.helm.sh/helm-{{version}}-linux-amd64.tar.gz"
          token: "${{ secrets.GITHUB_TOKEN }}"
      - name: "Run `helm template`"
        run: "make test-helm"
