name: "Lint"
on:
  push:
    branches:
      - "!dependabot/*"
      - "main"
  pull_request:
    branches: ["*"]
jobs:
  lint:
    name: "Lint"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0" # v7.0.0
      - uses: "actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16" # v6.5.0
        with:
          go-version-file: "go.mod"
      - name: "Run Go Linters"
        run: "make lint-go"
      - name: "Run YAML Linter"
        run: "make lint-yaml"
